package org.zhangmz.pickles.orm.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Transient;
import org.apache.commons.lang3.StringUtils;
import org.zhangmz.pickles.modules.utils.DiscuzHashPassword;
import org.zhangmz.pickles.modules.vo.DiscuzHashPasswordResult;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    @Id
    @Column(name = "Id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.hash_password
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    private String hashPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.salt
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.register_date
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.group_id
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.phone
     *
     * @return the value of account.phone
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.phone
     *
     * @param phone the value for account.phone
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setPhone(String phone) {
    	if(StringUtils.isNotBlank(phone)) this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setName(String name) {
    	if(StringUtils.isNotBlank(name)) this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setEmail(String email) {
    	if(StringUtils.isNotBlank(email)) this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.hash_password
     *
     * @return the value of account.hash_password
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public String getHashPassword() {
        return hashPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.hash_password
     *
     * @param hashPassword the value for account.hash_password
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setHashPassword(String hashPassword) {
        this.hashPassword = hashPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.salt
     *
     * @return the value of account.salt
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.salt
     *
     * @param salt the value for account.salt
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.register_date
     *
     * @return the value of account.register_date
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.register_date
     *
     * @param registerDate the value for account.register_date
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.group_id
     *
     * @return the value of account.group_id
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.group_id
     *
     * @param groupId the value for account.group_id
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.status
     *
     * @return the value of account.status
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.status
     *
     * @param status the value for account.status
     *
     * @mbggenerated Fri Jan 22 20:19:45 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Transient
    private Integer page = 1;

    @Transient
    private Integer rows = 10;
    
    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getRows() {
        return rows;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }
    
    /**
     * 接收页面的password
     * 与数据库的hash_password存在映射关系
     */
    @Transient
    private String password;

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
		
		// 在这里设置hash_password成员变量
		// 设置为Discuz加密方式，为数据迁移做准备
		DiscuzHashPasswordResult result = DiscuzHashPassword.getDiscuzHashPasswordResult(password);
		this.hashPassword = result.getHashPassword();
		this.salt = result.getSalt();
	}
}