package org.zhangmz.pickles.orm.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.id
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    @Id
    @Column(name = "Id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.code
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_name
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.admin_name
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.phone
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.register_date
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.status
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.note
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.id
     *
     * @return the value of groups.id
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.id
     *
     * @param id the value for groups.id
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.code
     *
     * @return the value of groups.code
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.code
     *
     * @param code the value for groups.code
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_name
     *
     * @return the value of groups.group_name
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_name
     *
     * @param groupName the value for groups.group_name
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.admin_name
     *
     * @return the value of groups.admin_name
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.admin_name
     *
     * @param adminName the value for groups.admin_name
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.phone
     *
     * @return the value of groups.phone
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.phone
     *
     * @param phone the value for groups.phone
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.register_date
     *
     * @return the value of groups.register_date
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")  
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.register_date
     *
     * @param registerDate the value for groups.register_date
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.status
     *
     * @return the value of groups.status
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.status
     *
     * @param status the value for groups.status
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.note
     *
     * @return the value of groups.note
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.note
     *
     * @param note the value for groups.note
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    public void setNote(String note) {
        this.note = note;
    }
}