package org.zhangmz.pickles.orm.model;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

public class Navtree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navtree.id
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    @Id
    @Column(name = "Id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navtree.pid
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navtree.name
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navtree.href
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navtree.param
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navtree.status
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navtree.id
     *
     * @return the value of navtree.id
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navtree.id
     *
     * @param id the value for navtree.id
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navtree.pid
     *
     * @return the value of navtree.pid
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navtree.pid
     *
     * @param pid the value for navtree.pid
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navtree.name
     *
     * @return the value of navtree.name
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navtree.name
     *
     * @param name the value for navtree.name
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navtree.href
     *
     * @return the value of navtree.href
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navtree.href
     *
     * @param href the value for navtree.href
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navtree.param
     *
     * @return the value of navtree.param
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navtree.param
     *
     * @param param the value for navtree.param
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public void setParam(String param) {
        this.param = param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navtree.status
     *
     * @return the value of navtree.status
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navtree.status
     *
     * @param status the value for navtree.status
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }
}