package org.zhangmz.pickles.orm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Select;
import org.zhangmz.pickles.modules.vo.IdName;
import org.zhangmz.pickles.orm.model.Group;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    Group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Tue Mar 01 18:02:05 CST 2016
     */
    int updateByPrimaryKey(Group record);
    
    /**
     * 根据条件查询
     * @param record
     * @return
     */
    List<Group> select(Group record);    

    /**
     * 根据条件查询
     * @param record
     * @return 只查询id/name两个字段，用于下拉列表显示
     */
    List<IdName> selectIdName(Group record);
    
}