package org.zhangmz.pickles.orm.mapper;

import org.zhangmz.pickles.orm.model.Navtree;

public interface NavtreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navtree
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navtree
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    int insert(Navtree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navtree
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    int insertSelective(Navtree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navtree
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    Navtree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navtree
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    int updateByPrimaryKeySelective(Navtree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navtree
     *
     * @mbggenerated Thu Jan 28 15:45:27 CST 2016
     */
    int updateByPrimaryKey(Navtree record);
}